# Generated by Django 5.0.6 on 2024-07-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymmembers",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gymmembers",
            name="renew_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
